{% set version = "1.4.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-hardhat
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/hardhat_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/hardhat/hardhat_{{ version }}.tar.gz
  sha256: 62f5f9e882a87ee0914438298ef27f89ded94568c5b1aed54c5189eeab186020

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-cli >=3.6.0
    - r-glue >=1.6.2
    - r-rlang >=1.1.0
    - r-sparsevctrs >=0.2.0
    - r-tibble >=3.2.1
    - r-vctrs >=0.6.0
  run:
    - r-base
    - r-cli >=3.6.0
    - r-glue >=1.6.2
    - r-rlang >=1.1.0
    - r-sparsevctrs >=0.2.0
    - r-tibble >=3.2.1
    - r-vctrs >=0.6.0

test:
  commands:
    - $R -e "library('hardhat')"           # [not win]
    - "\"%R%\" -e \"library('hardhat')\""  # [win]

about:
  home: https://github.com/tidymodels/hardhat
  license: MIT
  summary: Building modeling packages is hard. A large amount of effort generally goes into providing an implementation for a new method that is efficient, fast, and correct, but often less emphasis is put on the user interface. A good interface requires specialized knowledge about S3 methods and formulas, which the average
    package developer might not have. The goal of 'hardhat' is to reduce the burden around building new modeling packages by providing functionality for preprocessing, predicting, and validating input.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: hardhat
# Title: Construct Modeling Packages
# Version: 0.1.1
# Authors@R: c( person("Davis", "Vaughan", , "davis@rstudio.com", c("aut", "cre")), person("Max", "Kuhn", , "max@rstudio.com", c("aut")), person("RStudio", role = "cph"))
# Maintainer: Davis Vaughan <davis@rstudio.com>
# Description: Building modeling packages is hard. A large amount of effort generally goes into providing an implementation for a new method that is efficient, fast, and correct, but often less emphasis is put on the user interface. A good interface requires specialized knowledge about S3 methods and formulas, which the average package developer might not have. The goal of 'hardhat' is to reduce the burden around building new modeling packages by providing functionality for preprocessing, predicting, and validating input.
# License: MIT + file LICENSE
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 7.0.2
# Suggests: recipes (>= 0.1.8), testthat (>= 2.1.0), covr, knitr, rmarkdown, usethis, roxygen2, devtools
# Imports: glue, rlang (>= 0.4.1), tibble, vctrs (>= 0.2.0)
# URL: https://github.com/tidymodels/hardhat
# BugReports: https://github.com/tidymodels/hardhat/issues
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2020-01-07 15:27:41 UTC; davis
# Author: Davis Vaughan [aut, cre], Max Kuhn [aut], RStudio [cph]
# Repository: CRAN
# Date/Publication: 2020-01-08 23:01:24 UTC
